Android2week
KUIT-2/Android_1_DGmarket_clone pull request #12
Opened 2023-09-28 00:59 UTC by jhn1234570

2023-09-28 18:44 UTC, nonaninona requested changes
2주치 미션 코드 리뷰 내용입니다~

id주는 방식과, constraint를 이용하지 않고 margin으로 조정하는 방식을 수정하면 좋을 것 같습니다~

색깔 추가 등 나머지는 잘하셨어요!

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/java/com/example/carrotmarket/Alert_info_activity.kt
Activity 클래스 이름은
MainActivity처럼
PascalStyle을 따르는 것이 좋습니다~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/java/com/example/carrotmarket/HomeFragment.kt
>          }
2번째 itemLayout에도 클릭 시 화면 전환 추가해주세요~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/activity_alert_info.xml
> +            app:layout_constraintTop_toTopOf="parent"/>
지금은 marginStart와 marginEnd를 이용해서 두 텍스트 뷰의 간격을 조절을 해놓으셨네요.
그런데 만약 디바이스 화면의 총 width가 360dp가 아니라 320로 바뀐다면 어떻게 될까요?
최대한 constraint를 이용하는 것이 좋습니다.

텍스트 뷰를 각각 1/4과 3/4 지점에 놓으려면 어떻게 해야할까요?
1. 정 가운데에 constraint 용으로 사용할 view를 하나 놓는다
2. (추천) width의 반을 차지하는 constraintLayout 2개를 구성하고 그 안에 textView를 넣는다.

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                    android:src="@drawable/white_bar" />
이렇게 하얀색 이미지를 넣어줄 필요가 없고
parent인 constraintLayout의 background 속성에 white 색상을 넣어주면 됩니다.

이미지도 뭔가 이상한 상태네요.
꼭 가상기기로 실행해서 화면이 의도대로 나오는 지 확인하시길 바랍니다!
preview는 100% 신뢰할 수 없습니다~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                app:layout_constraintVertical_bias="1.0" />
iv_computer_user를 이용하면 bias를 주지 않고 배치할 수 있을 것 같습니다!

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                android:layout_marginEnd="70dp"
이렇게 margin으로 주는 것보다 constraint를 이용하는 것이
디바이스 화면의 크기가 변했을 때 더 안전합니다!

예를 들어 디바이스 너비가 360dp가 아니라 320dp로 변하면 엄청나게 깨질 수 있겠죠?
웃고있는얼굴 ImageView를 이용하는 것이 바람직합니다

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                android:id="@+id/imageView4"
id 이렇게 지으시면 프로젝트 때 협업자는 물론 본인도 알아보기 힘들어집니다.
1주차 미션 코드 리뷰를 참조해주세요

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/fragment_alert.xml
activity_alert_info.xml이 있으니
얘는 필요 없겠네요 삭제해주세요~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
이제는 없는 activity는 삭제해주세요~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/fragment_home.xml
> +            app:layout_constraintEnd_toEndOf="parent"/>
이 친구는 없어도 될 것 같은데요?~

2023-09-28 18:44 UTC, nonaninona commented on app/src/main/res/layout/fragment_my.xml
이 내용은 3주차 미션하면서 알아서 하실 것 같지만 언급하겠습니다
stuff_info_activity로 옮겼으니 삭제하셔도 될 것 같습니다~

2023-10-01 22:15 UTC, hyuns66 commented
main 말구 janghyungjoon  브랜치로 PR 보내주세요~

2023-10-05 02:33 UTC, closed without merging