submit
KUIT-2/Android_1_DGmarket_clone pull request #8
Opened 2023-09-20 12:52 UTC by gsuho

2023-09-25 17:22 UTC, hyuns66 reviewed
강의에서 진행한 내용을 바탕으로 잘 작성하셨고 나름 고민한 흔적도 보입니다.
하지만 실제 서비스 상황에서 동적으로 바뀔 수 있는 UI를 일관성있게 보이도록 하기위해 고려해봤으면 좋을 부분들에 대해 몇자 적어보았으니 꼭 읽어보시고 무슨의미인지 이해하고 넘어가면 좋겠습니다!

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +            android:src="@drawable/screenshot_macbook"/>
가장 메인이 되는 상단의 이미지를 가로를 꽉차게 주고 높이는 이미지 비율에 따라 자율적으로 늘어나게 하려고 하신것 같습니다. 그게 목적이었다면 adjustViewBind 속성을 함께 사용해서 이미지 비율을 유지하도록 해주어야 하는데 과연 이렇게 구현하는게 일관성있는 UI를 구성할 수 있을까요?
만약 main_image에 걸리는 사진의 높이가 일정치 않게 된다면 height가 wrap_content이므로 매번 이미지뷰의 높이가 달라질 것입니다.
그렇게 되면 일관성있는 UI가 아니라 매번 들쭉날쭉한 UI를 보게 되므로 사용자경험에 안좋은 영향을 미칠 수 있습니다. 따라서 고정된 크기를 가지도록 ImageVIew를 생성해주고, 빈공간을 어떻게 채워줄지 고려해서 설계하는 것이 일관성있는 UI를 구성하는 방법입니다!

```suggestion
        <ImageView
            android:id="@+id/main_image"
            android:layout_width="match_parent"
            android:layout_height="400dp"
            android:scaleType="centerCrop" 
            android:src="@drawable/screenshot_macbook"/>
```

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
파일명을 scroll_view로 지었는데 이렇게 하면 나중에 레이아웃 파일이 많아졌을 때 찾기 힘듭니다.
안드로이드 프로젝트 구조 특성상 layout 디렉토리안에는 서브 디렉토리를 넣을 수 없기 때문에 파일명으로 계층구조를 명확히 하면 좋습니다.

보통 코틀린 파일을 만들 때 MainActivity, SubActivity, HomeFragment, MyFragment 등으로 네이밍을 하게 됩니다.
그렇다면 각 화면을 이루는 액티비티와 프래그먼트에 매칭되는 레이아웃 파일이름 역시
activity_main, activity_sub, fragment_home, fragment_my 등으로 이름을 짓게 된다면 앞글자인 activity, fragment 에 따라 정렬되므로 파일이 많아져도 찾기 쉬워지겠죠??
보통 이런 식으로 규칙에 따라 이름을 짓는 행위를 네이밍 컨벤션 이라 부르는데 파일명 외에도 레이아웃 뷰의 각 아이디나 변수명 등을 자신만의 규칙에 맞게 네이밍 컨벤션을 하는것은 가독성 좋은 코딩을 하는데 도움이 되니까 꼭 신경써주세요!

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +            android:layout_margin="20dp"/>
위에서 말씀드린 네이밍 컨벤션 관련해서 보완할 점을 첨언해보자면 안드로이드 리소스의 모든 레이아웃에 있는 뷰 들은 각각 독립적인 id이름을 가져야 합니다.
만약 다른 fragment_home.xml 레이아웃 파일에도 동일하게 share 아이디가 들어간다면 에러가 나면서 빌드되지 않습니다. 따라서 View의 id값은 어떤 파일에 속했는지, 어떤 역할을 하는지, 무슨 타입의 view인지에 대한 정보도 나타날 수 있다면 더 좋습니다.
저같은 경우는 iv_home_share 과 같이 네이밍을 하는데 (home fragment 안에 있는 share 역할을 수행하는 image view라는 뜻) 이대로 진행하셔도 좋고
https://skyksit.com/programming/android/android-coding-style/
위 블로그 글에도 비슷한 내용이 있으니 한번 참고해보시면 좋을것 같아요

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +        android:layout_height="match_parent">
전체 ScrollVIew를 하나의 레이아웃으로 감싸고 있는데, height를 match_parent인 고정값으로 지정해두었습니다. 당근마켓에서 글쓰기를 하면 설명글을 작성자 역량껏 작성할 수 있는데, 만약 설명글을 너무 많이 작성하여 고정값으로 선언된 높이 match_parent를 넘어가면 어떻게 될까요? 그 밑의 글은 잘려서 보이지 않게 될 뿐더러 더 아래에 있어야 할 컨텐츠조차 볼 수 없게 되어버립니다.

즉 ScrollView 안에 Layout을 넣었다면 해당 Layout의 height에 wrap_content를 주어 가변길이를 가지도록 해주어야 컨텐츠 길이에 맞게 동적으로 늘어나 스크롤이 가능하게 됩니다.

```suggestion
    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
```

또한 하나의 ConstraintLayout안에 모든 뷰를 다 배치하는 것은 UI의 구성이 복잡해지고 그에 따라 예상치 못하게 UI가 깨지는 경우가 생길 수 도 있습니다. 당근마켓의 실제 화면을 보면  

- 매너온도와 프로필이 있는 섹션
- 제목과 카테고리, 작성날짜가 있는 섹션
- 상세정보 및 스펙을 작성한 본문 섹션

으로 나눠 볼 수 있습니다. (개인적인 시각의 차이가 있겠으나 UI의 부분을 각각의 섹션으로 나눌 수 있다는 뜻으로 이해해주세요!) 그렇게 되면 각각의 섹션을 작은 레이아웃으로 구성하여 전체 큰 레이아웃 안에 포함시키는 방식으로 UI를 구성한다면, 가독성이 좋아질 뿐 더러 View의 모음들이 하나의 작은 레이아웃으로 묶여 컴포넌트화 되기 때문에 UI 오류의 확률을 줄일 수 있습니다.

요약하면 
```xml
<Layout>
    <View/>
    <View/>
    <View/>
    <View/>
    <View/>
    <View/>
</Lyaout>
```
형식보단
```xml
<Layout>
    <Layout>
        <View/>
        <View/>
    </Layout>
    <Layout>
        <View/>
        <View/>
    </Layout>
    <Layout>
        <View/>
        <View/>
    </Layout>
</Lyaout>
```
형식으로 각각의 섹션을 컴포넌트화 해서 UI를 구성하는 연습을 해보시면 좋을것 같아요!

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +            android:layout_margin="10dp"/>
당근마켓에서는 프로필 이미지가 동그란 모양으로 되어 있을 것입니다.
따라서 ImageView를 동그랗게 만드는 방법에 대해 찾아보시면 좋을것 같아요
hint : CardView, MaterialCardView

2023-09-25 17:22 UTC, hyuns66 commented on app/src/main/res/layout/scroll_view.xml
> +            android:textSize="15sp"/>
본문 내용을 나타내는 TextView 인데 width가 wrap_content로 되어 있습니다. 이렇게 되면 텍스트의 길이에 따라 무작정 너비가 늘어나기 때문에 화면밖으로 나가 잘리는 부분이 발생하게 됩니다.
따라서 TextView를 화면 안에 온전히 표시하고싶다면 width를 match_parent로 주어야 화면 범위 내에서 온전히 표시가 되게 됩니다.
또한 text를 연속적인 띄어쓰기를 통해 줄바꿈을 표현한 것으로 보이는데, 줄바꿈 문자 "\n" 를 활용하면 enter의 효과를 구현할 수 있습니다.
일반 문자열에서 표현할 수 없는 줄바꿈이나 각종 특수문자들을 표현하기 위한 이스케이프 문자 라는것이 있으니 시간날때 한번 찾아보시고 이런게 있다 정도만 알고계셔도 좋을것 같습니다!

2023-09-28 17:40 UTC, nonaninona commented
2주차 과제 리뷰입니다

전체적으로 naming이나 constraint가 조금씩 아쉬운 부분이 있습니다

학년을 고려하면 진짜 잘 따라오고 있으니 리뷰 내용 반영하고 3주차 과제도 화이팅해요~

2023-09-28 18:08 UTC, nonaninona requested changes
2주차 과제 리뷰입니다

전체적으로 naming이나 constraint가 조금씩 아쉬운 부분이 있습니다

학년 고려했을 때 진짜 잘 따라오고 있으니 리뷰 내용 반영하고 3주차 과제도 화이팅해요~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/java/com/example/carrotmarket/Notification.kt
Activity의 Class 이름은
MainActivity처럼 뒤에 Activity를 붙여주는 게 좋아요~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/java/com/example/carrotmarket/StuffInfoActivity.kt
> +            val intent_stuffinfo_to_main = Intent(this,MainActivity::class.java)
kotlin 공식문서에서는
지역변수 이름을 camelStyle로 작성하길 권장하고 있어용~
https://developer.android.com/kotlin/style-guide#non-constant_names

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_main.xml
main activity는 bottom navigation view와
bottom navigation view에서 탭을 선택하면 변화하는 frame layout으로 구성되어있고
frame layout에 들어가는 fragment들이 있습니다(home, mypage 등등)

그런데 이렇게 main activity에다가 home fragment의 ui를 그대로 넣어버리면
항상 home 화면이 보이게 되는데요
실행해서 bottom navigation의 다른 메뉴를 눌러보면 뭐가 문제인지 바로 알 것 같아요~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_notification.xml
> +            app:layout_constraintTop_toTopOf="@id/notification_top_app_bar"
notification_top_app_bar는 parent로 작성하면 더 짧고
유지보수에도 좋을 것 같아요~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_notification.xml
> +            app:layout_constraintEnd_toEndOf="@id/notification_selection_alarms"
'키워드 알림' '활동 알림' 두가지의 textView의 배치를
이렇게 marginStart 속성에 특정 값을 줘서 조절해버리면

디바이스의 width가 360dp가 아니라
320dp가 되버리면 생각한 비율이 되지 않을 가능성이 높습니다~

그래서 최대한 constraint로 해결하는 것이 좋은데요
화면의 중앙에 view를 하나 위치 시켜서
두 개의 textView의 constraint에 활용하거나

(추천) 화면의 width를 양분하는 constraintLayout 2개를 만들어서
그 안에 각각 textView를 넣는 것이 좋아보이네요~
이런 constraintLayout을 만드려면 밑에 scrollView에 활용했던 방식처럼 width를 0으로  해야겠죠?

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +
margin으로 해결하지 않고
top과 bottom constraint를 각각 back_arrow의 top과 bottom에 붙여주면
back arrow icon과 home icon이 수직으로 정렬됩니다~
그게 더 좋은 방법 같네요!

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +    <com.google.android.material.bottomnavigation.BottomNavigationView
bottomNavigationView 위젯을 전혀 쓸 필요가 없습니다~!
bottomNavigation의 역할을 하는 부분이 아니기 때문이죵

그냥 constraintLayout으로 구현하는 걸 추천드립니다.

밑에 붙이는건 bottomConstraint로 해결할 수 있어요~
밑에 있는 ScrollView의 bottom을 이 constraintLayout의 top에 붙여주면 되겠죵

```suggestion
    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:layout_constraintBottom_toBottomOf="parent"
```

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +        <LinearLayout
LinearLayout의 자식 위젯들에 Constraint 속성들을 사용하고 있네요
여기서 구현하는 하단바는 ConstraintLayout이 적절해보입니다

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                android:layout_height="wrap_content"
당근마켓 앱을 참고하면,
이렇게 큰 이미지를 사용하지는 않습니다~
height를 지정해주는 것이 좋을 것 같습니다!
scaleType이라는 속성도 확인해보세요~
https://sharp57dev.tistory.com/23

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                app:layout_constraintTop_toBottomOf="@+id/main_image" />
main image를 전체 너비로 사용하지 않게 변경한다면 어떻게 될까요?
ImageView가 속한 constraint layout을 주는 것이 나아보입니다

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                app:layout_constraintBottom_toTopOf="@id/line_for_profile_explain"
line보다는 얼굴 이미지를 활용하면 포지셔닝이 더 좋을 것 같은데요

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +            <ImageView
progress bar, seek bar라는 위젯을 이용하는 것이 제일 좋고,
cardView로 radius 속성을 주는 것도 좋아보입니다.
저희가 구현까지는 안하겠지만 이 온도계가 숫자에 따라 변해야하기 때문에
이미지로 넣는 것은 매번 바꿔줘야 하니까 적절하지 않아보여요

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                app:layout_constraintBottom_toTopOf="@id/line_for_profile_explain"
profile 정보들을 담는 constraintLayout을 넣는 것이 좋아보입니다
그러면 line의 위치도 적절하게 정해지겠죠~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/activity_stuff_info.xml
> +                                     고급형 : 8GB/512GB/10코어 거의 새상품입니다."
text 속성에 엔터를 넣어줘도 개행이 안됩니다.
자바 때 배운 것처럼 \n을 넣어주면 되요~

2023-09-28 18:08 UTC, nonaninona commented on app/src/main/res/layout/scroll_view.xml
activity_stuff_info.xml이 있으니 얘는 삭제해도 좋을 것 같습니다~

2023-11-06 10:07 UTC, closed without merging